CREATE TABLE Accounts (
    ACCOUNT_ID VARCHAR(255)  PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_MOBILE VARCHAR(15) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
    ADDRESS_1 VARCHAR(255) NOT NULL,
    ADDRESS_2 VARCHAR(255),
);