CREATE TABLE PARKING_LOT(
    PARKING_LOT_ID varchar(50) PRIMARY KEY,
    LOCATION varchar(255),
    COST_PER_MINUTE INT
);

CREATE TABLE LOT(
    LOT_ID varchar(50) PRIMARY KEY,
    IS_AVAILABLE BOOLEAN NOT NULL,
    PARKED_CAR_DETAIL VARCHAR(255),
    LOT_LOCATION VARCHAR(255),
    PARKED_TIME DATE
)